/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rest.assured.teste;

import io.restassured.http.ContentType;
import org.apache.http.HttpStatus;
import org.junit.Test;
import rest.assured.dominio.Usuario;

import static io.restassured.RestAssured.given;
import static org.hamcrest.Matchers.is;
import static org.hamcrest.Matchers.notNullValue;

public class UsuarioTeste extends BaseTeste {

    @Test public void testListUserMetadata() {
        given().
                param("page", "2").
        when().
                get("/users").
        then().
                statusCode(HttpStatus.SC_OK).
                body("page", is(2)).
                body("data", is(notNullValue()));
    }

    @Test public void testSucessfullyCreateaUser(){
        Usuario usuario = new Usuario("rafael", "eng test", "email@gmail.com");
        given().
                body(usuario).
        when().
                post("/users").
        then().
                statusCode(HttpStatus.SC_CREATED).
                body("name", is("rafael"));
    }
}
